// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRJc3Sbm64tOe3_1tLVoj30nhc5tPUlA',
    appId: '1:291131728748:web:4dd1ea7a568118f73f0949',
    messagingSenderId: '291131728748',
    projectId: 'sign-in-example-9ba86',
    authDomain: 'sign-in-example-9ba86.firebaseapp.com',
    storageBucket: 'sign-in-example-9ba86.firebasestorage.app',
    measurementId: 'G-X4L8V0QX73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI0wxS-UFNraMTXfUxzUkSqzCMSnCvIug',
    appId: '1:291131728748:android:0e7b1ce8f69e8c7e3f0949',
    messagingSenderId: '291131728748',
    projectId: 'sign-in-example-9ba86',
    storageBucket: 'sign-in-example-9ba86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dhaBs_PEuMicYWw0GWuJ_nJk4yD9jTc',
    appId: '1:291131728748:ios:cd255f9cd37bc8c33f0949',
    messagingSenderId: '291131728748',
    projectId: 'sign-in-example-9ba86',
    storageBucket: 'sign-in-example-9ba86.firebasestorage.app',
    androidClientId:
        '291131728748-jmid74269li9u8u6t3lcmv8c0t2o7261.apps.googleusercontent.com',
    iosClientId:
        '291131728748-rmis1nc5ig1vvg1jm08bnf7846c2vnd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseproject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dhaBs_PEuMicYWw0GWuJ_nJk4yD9jTc',
    appId: '1:291131728748:ios:cd255f9cd37bc8c33f0949',
    messagingSenderId: '291131728748',
    projectId: 'sign-in-example-9ba86',
    storageBucket: 'sign-in-example-9ba86.firebasestorage.app',
    androidClientId:
        '291131728748-jmid74269li9u8u6t3lcmv8c0t2o7261.apps.googleusercontent.com',
    iosClientId:
        '291131728748-rmis1nc5ig1vvg1jm08bnf7846c2vnd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseproject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYRJc3Sbm64tOe3_1tLVoj30nhc5tPUlA',
    appId: '1:291131728748:web:e9f30686761d02d03f0949',
    messagingSenderId: '291131728748',
    projectId: 'sign-in-example-9ba86',
    authDomain: 'sign-in-example-9ba86.firebaseapp.com',
    storageBucket: 'sign-in-example-9ba86.firebasestorage.app',
    measurementId: 'G-G8C7MY60F8',
  );
}
