import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

// This import is ESSENTIAL for Firebase.initializeApp to work.
// Ensure lib/firebase_options.dart is correctly generated by `flutterfire configure`
// and contains the actual configuration values for your project.
import 'package:firebaseproject2/firebase_options.dart'; // Or just 'firebase_options.dart' if in the same /lib dir

import 'package:firebaseproject2/screens/signin_screnn.dart';
import 'package:firebaseproject2/screens/home_screnn.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Load environment variables first
  await dotenv.load(fileName: ".env");  // Add this line
  
  await Firebase.initializeApp(
    // The options: DefaultFirebaseOptions.currentPlatform line is critical.
    // It uses the firebase_options.dart file.
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Health & Fitness AI Agent',
      debugShowCheckedModeBanner: false, // Good to keep this off for cleaner UI
      theme: ThemeData(
        // Using a very basic theme, or a default swatch.
        // You can specify a primarySwatch if you like.
        primarySwatch: Colors.blue, // Example default swatch
        // If you want to try Material 3 defaults without much customization:
        // useMaterial3: true,
        // colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple), // Example M3 seed
      ),
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            // Optionally, show a more branded splash screen here later
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          if (snapshot.hasData && snapshot.data != null) {
            return const HomeScreen(); // User is logged in
          }
          return const SignInScreen(); // User is not logged in
        },
      ),
    );
  }
}